### ISSUE TITLE
Lack of validation results in repeat messages

### ISSUE THREAD

**Issue by benstobbs** [Velocidex/evtx#16]
When multiple event providers use the same EventMessageFile (e.g `Microsoft-Windows-AppModel-Runtime` and `Microsoft-Windows-AppModel-State`), only part of the EventMessageFile pertains to each event provider. However, every message is processed for each provider.

This results in message duplications:
![image](https://user-images.githubusercontent.com/12483914/134479442-5202ea8c-e15c-4e22-a983-24ae1be6f9f5.png)

Apologies if I'm missing anything!

**Comment by scudette** [comment]
I dont quite follow - are you talking about the extract_windows program dumping out event messages?

I found that many message files contain duplicate messages all the time - this is just the way the message tables are built. It is so that the message id can be mapped back to the same string. 

Does it still render the correct message when parsing the evtx file?

**Comment by benstobbs** [comment]
this was a misunderstanding, sorry!
